name: docker

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: anzerr/docker.action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          args: |
            docker build -t anzerr/banano:20 -f docker/20/Dockerfile . &&
            docker push anzerr/banano:20 &&
            docker push anzerr/banano:latest &&
            docker build -t anzerr/banano:20-daemon -t anzerr/banano:latest-daemon -f docker/20/daemon/Dockerfile . &&
            docker push anzerr/banano:20-daemon &&
            docker push anzerr/banano:latest-daemon